### ISSUE TITLE
Does CONTRIBUTING.rst apply to this repo, too?

### ISSUE THREAD

**Issue by andylolz** [data4development/IATI-Rulesets#54]
The [contributing guide in this repo](https://github.com/data4development/IATI-Rulesets/blob/54a5b903b0396a0fd1baaed3dcca1f0448047004/CONTRIBUTING.rst) is forked from source. Does that mean it applies here, too?

I’ve spotted some issues with rules, so I wonder if you’d be interested in tickets / PRs?

Thanks

**Comment by rolfkleef** [comment]
hi Andy, tickets and PRs are welcome! We're working towards public beta launch, we have a couple of fixes ahead that we're aware of already so add a ticket before doing major PR work.

**Comment by andylolz** [comment]
Excellent, sounds good – thanks!
