### ISSUE TITLE
identifier_check isn’t run for `iati-activity/iati-identifier` 

### ISSUE THREAD

**Issue by andylolz** [data4development/IATI-Rulesets#55]
In the IATI standard, there’s currently an [`iati-identifier` rule](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/iati-identifier/#rules) that:

> `iati-identifier` should match the regex [^\/\&\|\?]+

Additionally, the [`iati-identifier` overview page](http://reference.iatistandard.org/203/activity-standard/overview/iati-identifier/#considerations) of the IATI standard reference site says:

> The `iati-identifier` should have no leading or trailing whitespace.

In this repo, these rules exist in [`identifier_check`](https://github.com/data4development/IATI-Rulesets/blob/6affe5da03b84f4e24335c1f4fe0108d1cb35e1b/rules/lib/identifiers.xslt#L9-L32) for [various identifiers](https://github.com/data4development/IATI-Rulesets/blob/6affe5da03b84f4e24335c1f4fe0108d1cb35e1b/rules/iati/identifiers.xslt#L43-L99), but not for `iati-activity/iati-identifier`.

This seems like it might be an accidental omission?

**Comment by rolfkleef** [comment]
An omission indeed, Andy.

**Comment by andylolz** [comment]
Okay, great – glad this was useful. Thanks for resolving it.

I’m slightly puzzled by one small thing in the fix… Wouldn’t it be better to either check `iati-activity/iati-identifier` [here](https://github.com/data4development/IATI-Rulesets/commit/67d8fba15ce77f7e7af65ea0f8c0c27565b67f7e#diff-e5f9ec4b3dbe039ac6e1638e72a86859R52), or remove [this bit](https://github.com/data4development/IATI-Rulesets/commit/67d8fba15ce77f7e7af65ea0f8c0c27565b67f7e#diff-e5f9ec4b3dbe039ac6e1638e72a86859R61-R69)?

I guess there is no problem with overlapping rules, but in this case it seems avoidable.

**Comment by rolfkleef** [comment]
It's a bit due to overlapping work actually: we're removing all version 1.0x checks from the validator still, and that includes the second bit you mention: the iati-organisation/iati-identifier is a v1.0x element.

**Comment by andylolz** [comment]
Aha – gotcha! Thanks for clarifying.
