### ISSUE TITLE
BUG: 7.8.1 does the wrong thing for `iati-organisation`s

### ISSUE THREAD

**Issue by andylolz** [data4development/IATI-Rulesets#59]
https://github.com/data4development/IATI-Rulesets/blob/04edd05d1b6f897e686b99f13342dfce584f99f9/rules/iati/financial.xslt#L52-L59

The template match clause doesn’t specify an `iati-activity`, but the check for a `default-currency` does. So `iati-organisation`s with a `default-currency` fall foul of this rule.

**Comment by andylolz** [comment]
[Confirmed elsewhere](https://github.com/data4development/IATI-data-validator/issues/43#issuecomment-553417819) by @rolfkleef that this is a bug. I’ve amended the title accordingly.

**Comment by andylolz** [comment]
I guess this is fixed in d9606a358c6184edd2e2c19380762d1e8f080a88, and can be closed now?

**Comment by rolfkleef** [comment]
thanks @andylolz!
